// Ағылшын фразалық етістіктерінің аудармалары
const phrasalVerbs = {
    "break up": "айырылысу, бөлу",
    "call off": "болдырмау, тоқтату",
    "give up": "бас тарту, тастау",
    "look after": "қамқор болу, қарау",
    "put off": "кейінге қалдыру",
    "take off": "көтерілу, ұшу",
    "run into": "кездесу, соқтығысу",
    "set up": "құру, орнату",
    "turn down": "бас тарту, азайту",
    "work out": "шешу, жаттығу жасау",
    "give away": "donate = беру, қайырымдылық жасау",
    "give back": "return = қайтару",
    "give in": "submit/hand in = берілу",
    "give out": "hand out = бөліп беру",
    "give off": "emit = бөліп шығару",
    "look after": "to take care of = бағу",
    "look for": "to search = іздеу",
    "look into": "to investigate = зерттеу",
    "look out": "to be careful = сақ болу",
    "look up": "to search for information (in a book, online, etc.) = жоғары қара",
    "keep up with": "to move at the same speed = ілесу",
    "keep on": "to continue = жалғастыру",
    "keep away": "to prevent access to, to hold back = алдын алу, болдырмау",
    "keep off": "to stay away = алшақ болу",
    "put aside": "to ignore, to forget = назар аудармау",
    "put away": "to put into usual place = алып қою, басқа жерге",
    "put off": "to postpone = кейінге қалдыру",
    "put on": "to start wearing = киіну",
    "put up with": "to tolerate = шыдау",
    "hang on": "to wait = кідіру, күту",
    "hang out": "to spend time = қыдыру",
    "hang up": "to put the phone down = трубканы қою",
    "hang around": "to wait around = айналада күту",
    "make up": "to invent = құрау, ойлап табу",
    "make up for": "to feel better after a bad experience = орнын толтыру",
    "make out": "to see smth that is unclear = түсініп алу",
    "make for": "to move towards a place = бағыт алу",
    "break down": "to decompose or to lose control of feelings = сыну",
    "break into": "to enter by force = басып кіру",
    "break out of": "to escape from = қашу",
    "break up": "to stop for holidays = демалыс алу",
    "turn up": "appear = пайда болу",
    "turn down": "refuse an offer, invitation, suggestion, etc. = бас тарту, сөндіру",
    "turn off": "switch off = сөндіру",
    "turn to smb": "go to smb for help = көмек сұрау",
    "turn into": "to change into smth = айналу",
    "run off": "go away = кету",
    "run across": "meet by chance = кездесу",
    "run away with": "escape with = қашып кету",
    "run after": "chase = қуу",
    "run into": "face (problems) = мәселеге тап болу",
    "run up": "accumulate = жинақтау",
    "run down": "(car batteries) go flat = жүктелу",
    "run out of": "have no more = бітіп қалу",
    "run over": "revise, go over, or drive over sth = қайталау, басып кету",
    "run along": "hurry up = тез кету",
    "break away": "escape = қашу",
    "break down": "(of machines) stop working = сыну",
    "break into": "enter by force = басып кіру",
    "break in": "break into = басып кіру",
    "break out": "(of fire) start = өртену",
    "break through": "force your way through a barrier = жарып өту",
    "set off": "to start a journey = саяхатқа шығу",
    "set back": "to delay = кідіру",
    "set aside": "to save for a special purpose/occasion = кейінге қалдыру",
    "set up": "to start = бастау",
    "keep off": "make sb stay away from = алшақтау",
    "keep smb down": "prevent sb from getting power = тоқтату",
    "keep on": "continue despite difficulties = жалғастыру",
    "keep out": "make sb/sth stay away = жібермеу",
    "keep up": "continue = жалғастыру, қолдау",
    "Carry over": "continue to exist = ауыстыру",
    "Carry on": "continue = жалғастыру",
    "Carry out": "(threat, task, instruction) = орындау",
    "Carry through": "complete despite difficulties = толық аяқтау",
    "Carry off": "do smth successfully, win = жеңу",
    "Come about": "happen = орын алу",
    "Come across": "meet by chance = кездесу",
    "Come down with": "become ill = ауыру",
    "Come down to": "be reduced to = басылу",
    "Come out": "publish = басып шығару",
    "Come off": "carry out = орындау",
    "Come up to": "approach = жақындау",
    "Come up with": "think of = ойлану",
    "bring about": "cause smth to happen = болдыру",
    "bring out": "publish = басып шығару, айрықша баса айту",
    "bring up": "raise (a child) = тәрбиелеу",
    "come across": "find smth by accident = кездейсоқ табу",
    "come down with": "catch an illness = науқастанып қалу",
    "come up with": "invent or discover smth = ойлап шығару",
    "back away": "move backwards from smth or smb = артқа шегіну",
    "back down": "give in, accept defeat = берілу",
    "back out": "decide not to do smth = бас тарту",
    "back up": "make a copy of a file, programme, etc. = резервтік көшірме жасау",
    "back sb up": "give support to smb = қолдау",
    "call sb back": "return smb’s phone call = қайта хабарласу",
    "call off": "cancel = қайтару",
    "carry on": "continue = жалғастыру",
    "carry out": "do smth as planned (a plan, order, threat), perform or conduct (repairs, research, test, etc.) = орындау",
    "look after": "take care of = қарау",
    "look into": "do research about, investigate = бір затты зерттеу",
    "look over": "examine quickly = қарап шығу",
    "look up to": "admire = сүйсіну",
    "try on": "put on clothing to see if it fits = киіп көру",
    "try out": "compete for a place (in a team) = сайысу",
    "try sth out": "use smth to see if it works/you like it = сынақтан өткізу",
    "do sth over": "repeat smth = қайтадан жасау",
    "do up": "1. fasten (clothes) 2. decorate (a room or building) = түймелеу, жөндеу",
    "drop by/in": "visit a place or a person = қонаққа кіріп шығу",
    "drop out": "leave before the end (school, college) = шығып кету",
    "get across": "make smb. understand, communicate = ойын толық жеткізу",
    "get ahead": "do well in a career = озу",
    "get along (with sb)": "be friendly with smb = біреумен жақсы қатынаста болу",
    "set off": "start a journey = жолға шығу",
    "set sth aside": "set smth. aside (money) = сақтап қою",
    "set up": "start a company = негізін қалау",
    "take in sth": "learn or understand smth = үйрену",
    "take over": "begin to have control = басқаруды бастау",
    "take up": "start (a hobby, sport) = бастау",
    "back down": "admit defeat = жеңілісті мойындау",
    "break down": "stop working = сыну",
    "close down": "cease to operate = жұмысты тоқтату",
    "cut down": "reduce = қысқарту",
    "live down": "forget = ұмыту",
    "turn down": "do not accept = бас тарту, қабылдамау",
    "keep away": "prevent access to, hold back = алыстату",
    "keep off": "stay away, prevent from stepping or climbing on smth = алшақ болу",
    "keep on": "continue = жалғастыру",
    "keep up with": "move at the same speed = ілесу",
    "let down": "disappoint = көңілін қалдыру",
    "let out (of)": "release from prison or captivity = босату",
    "pick on": "treat unkindly = кемсіту",
    "pick out": "choose = таңдау",
    "pick up": "lift with hands, take smb. away in a car = көтеру, көлікпен алып кету",
    "hand in": "submit = тапсыру",
    "hand out": "distribute = тарату",
    "hand over": "give (usually without wanting to) = беру",
    "hang out": "spend time relaxing = қыдыру",
    "hang on": "wait a short time = кідірту",
    "join in": "become involved in an activity with others = қатысу",
    "join up": "become a member of a club, etc. = қосылу",
    "hold on": "wait = күту",
    "get on": "have a good relationship = жақсы қарым-қатынаста болу",
    "catch on": "be popular = танымал болу",
    "look on": "watch = қарау",
    "pass smth on": "give sth to smb else = беру",
    "put on": "arrange an event = ұйымдастыру",
    "make up": "invent = ойлап табу",
    "spring up": "appear suddenly = көріну",
    "add up": "make sense = мағынасы болу",
    "steam up": "become covered in a layer of moisture = ылғалдану, булану",
    "act up": "not to work as it should = дұрыс істемеу",
    "come up": "get mentioned = еске салу",
    "fill out": "complete = аяқтау",
    "find out": "learn = үйрену, білу",
    "fall out": "argue = бәстесу",
    "work out": "understand = түсіну",
    "pass out": "faint = есінен тану",
    "point out": "bring to smb’s attention = назар аударту",
    "pay off": "settle the debt = қарызды жабу",
    "call off": "cancel = бас тарту",
    "put off": "delay = кейінге қалдыру",
    "show off": "try to impress = өзін көрсету",
    "drop off": "fall asleep = ұйықтап қалу",
    "take off": "become successful = табысты болу",
    "carry over": "continue to exist = бар болу",
    "blow over": "end = аяқтау",
    "win over": "persuade = сендіру",
    "sign over": "give legally = заңды түрде беру",
    "get over": "recover = емделу",
    "go over": "look at = қарау",
    "turn in": "give = беру",
    "fit in": "belong = тиесілі болу",
    "check in": "contact smb = байланысу",
    "fall in": "become friendly = дос болу",
    "pitch in": "do smth in a group = топқа қосылу",
    "settle in": "feel comfortable = ыңғайлы сезіну",
    "hold down": "keep = сақтау",
    "play down": "make seem insignificant = маңызсыз қылу",
    "mark down": "reduce price = арзандату",
    "water down": "make weaker = жұмсарту",
    "step down": "resign = отставкаға шығу",
    "narrow down": "reduce number = санын азайту"
};

// Функция аудару үшін
function translatePhrasalVerb() {
    const input = document.getElementById('phrasalVerb').value.trim().toLowerCase();
    const result = document.getElementById('result');

    // Егер сөз сөздікте бар болса, тек аудармасын көрсетеміз
    if (phrasalVerbs.hasOwnProperty(input)) {
        result.textContent = phrasalVerbs[input]; // Тек аудармасын көрсетеді
    } else {
        result.textContent = "Фразалық етістік табылмады.";
    }
}

// Батырманы басқан кезде аудару функциясын шақырамыз
document.getElementById('translateButton').addEventListener('click', translatePhrasalVerb);